name: Sync Riot Stats

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests
      - name: Run update script
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        run: python update_stats.py
      - name: Commit & push stats.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add stats.json
          git commit -m "Auto-sync Riot stats"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}