name: Sync Riot Stats

# Déclenchement manuel et toutes les heures
on:
  schedule:
    - cron: '0 * * * *'      # toutes les heures
  workflow_dispatch:       # bouton “Run workflow” dans l’UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code
      - uses: actions/checkout@v3

      # 2) Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Installer la dépendance requests
      - name: Install dependencies
        run: pip install requests

      # 4) Lancer le script de mise à jour
      - name: Run update script
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        run: python update_stats.py

      # 5) Commit & push du nouveau stats.json
      - name: Commit & push stats.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add stats.json
          git commit -m "Auto-sync Riot stats"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
